# Automatically generated by configure - do not modify
include ../config-host.mak
TARGET_ARCH=ppcemb
TARGET_ABI_DIR=ppc
TARGET_WORDS_BIGENDIAN=yes
CONFIG_SOFTMMU=yes
TARGET_XML_FILES= /root/faultxen/tools/qemu-xen-traditional/gdb-xml/power-core.xml /root/faultxen/tools/qemu-xen-traditional/gdb-xml/power-fpu.xml /root/faultxen/tools/qemu-xen-traditional/gdb-xml/power-altivec.xml /root/faultxen/tools/qemu-xen-traditional/gdb-xml/power-spe.xml
CONFIG_SOFTFLOAT=yes
