fsys_iso9660.opic: fsys_iso9660.c \
 ../../../tools/libfsimage/common/xenfsimage_grub.h \
 ../../../tools/libfsimage/common/xenfsimage.h \
 ../../../tools/libfsimage/common/xenfsimage_plugin.h \
 iso9660.h
