xl_cdrom.o: xl_cdrom.c ../../tools/config.h \
 ../../tools/libxl/libxl.h \
 ../../tools/libs/toollog/include/xentoollog.h \
 ../../tools/libxl/libxl_uuid.h \
 ../../tools/libxl/_libxl_list.h \
 ../../tools/libxl/_libxl_types.h \
 ../../tools/libxl/libxl_event.h \
 ../../tools/libxl/libxl_utils.h \
 ../../tools/libxl/libxl.h \
 ../../tools/libxl/libxlutil.h xl.h _paths.h \
 xl_utils.h xl_parse.h
