fsi_zfs.opic: fsi_zfs.c \
 ../../../tools/libfsimage/common/xenfsimage_grub.h \
 ../../../tools/libfsimage/common/xenfsimage.h \
 ../../../tools/libfsimage/common/xenfsimage_plugin.h \
 ../../../tools/libfsimage/common/fsimage_priv.h \
 mb_info.h
