zfs_sha256.opic: zfs_sha256.c fsys_zfs.h fsi_zfs.h \
 ../../../tools/libfsimage/common/xenfsimage_grub.h \
 ../../../tools/libfsimage/common/xenfsimage.h \
 ../../../tools/libfsimage/common/xenfsimage_plugin.h \
 mb_info.h \
 ../../../tools/libfsimage/zfs/zfs-include/zfs.h \
 ../../../tools/libfsimage/zfs/zfs-include/dmu.h \
 ../../../tools/libfsimage/zfs/zfs-include/spa.h \
 ../../../tools/libfsimage/zfs/zfs-include/zio.h \
 ../../../tools/libfsimage/zfs/zfs-include/zio_checksum.h \
 ../../../tools/libfsimage/zfs/zfs-include/vdev_impl.h \
 ../../../tools/libfsimage/zfs/zfs-include/zap_impl.h \
 ../../../tools/libfsimage/zfs/zfs-include/zap_leaf.h \
 ../../../tools/libfsimage/zfs/zfs-include/uberblock_impl.h \
 ../../../tools/libfsimage/zfs/zfs-include/dnode.h \
 ../../../tools/libfsimage/zfs/zfs-include/dsl_dir.h \
 ../../../tools/libfsimage/zfs/zfs-include/zfs_acl.h \
 ../../../tools/libfsimage/zfs/zfs-include/zfs_znode.h \
 ../../../tools/libfsimage/zfs/zfs-include/dsl_dataset.h \
 ../../../tools/libfsimage/zfs/zfs-include/zil.h \
 ../../../tools/libfsimage/zfs/zfs-include/dmu_objset.h \
 ../../../tools/libfsimage/zfs/zfs-include/sa_impl.h
