static_tables.o: \
 ../../tools/libacpi/static_tables.c \
 ../../tools/config.h \
 ../../tools/libacpi/acpi2_0.h \
 ../../tools/include/xen/xen.h \
 ../../tools/include/xen/xen-compat.h \
 ../../tools/include/xen/arch-x86/xen.h \
 ../../tools/include/xen/arch-x86/../xen.h \
 ../../tools/include/xen/arch-x86/xen-x86_64.h \
 ../../tools/include/xen/hvm/ioreq.h \
 ../../tools/libacpi/../config.h
