seabios.o: seabios.c config.h config-seabios.h util.h \
 ../../../tools/include/xen/xen.h \
 ../../../tools/include/xen/xen-compat.h \
 ../../../tools/include/xen/arch-x86/xen.h \
 ../../../tools/include/xen/arch-x86/../xen.h \
 ../../../tools/include/xen/arch-x86/xen-x86_32.h \
 ../../../tools/include/xen/hvm/hvm_info_table.h \
 e820.h \
 ../../../tools/include/xen/errno.h \
 smbios_types.h ../../libacpi/acpi2_0.h \
 ../../../tools/include/xen/hvm/ioreq.h \
 ../../libacpi/libacpi.h
