# Automatically generated by configure - do not modify
include ../config-host.mak
TARGET_ARCH=m68k
TARGET_WORDS_BIGENDIAN=yes
CONFIG_SOFTMMU=yes
TARGET_XML_FILES= /root/xen-4.13.0/tools/qemu-xen-traditional/gdb-xml/cf-core.xml /root/xen-4.13.0/tools/qemu-xen-traditional/gdb-xml/cf-fp.xml
CONFIG_SOFTFLOAT=yes
