tcgbios.o: tcgbios.c ../rombios_compat.h ../../32bitprotos.h \
 tpm_drivers.h ../util.h ../../../../libacpi/acpi2_0.h \
 ../../../../../tools/include/xen/xen.h \
 ../../../../../tools/include/xen/xen-compat.h \
 ../../../../../tools/include/xen/arch-x86/xen.h \
 ../../../../../tools/include/xen/arch-x86/../xen.h \
 ../../../../../tools/include/xen/arch-x86/xen-x86_32.h \
 ../../../../../tools/include/xen/hvm/ioreq.h \
 tcgbios.h
