# Automatically generated by configure - do not modify
include ../config-host.mak
TARGET_ARCH=arm
CONFIG_USER_ONLY=yes
CONFIG_LINUX_USER=yes
TARGET_XML_FILES= /root/faultxen/tools/qemu-xen-traditional/gdb-xml/arm-core.xml /root/faultxen/tools/qemu-xen-traditional/gdb-xml/arm-vfp.xml /root/faultxen/tools/qemu-xen-traditional/gdb-xml/arm-vfp3.xml /root/faultxen/tools/qemu-xen-traditional/gdb-xml/arm-neon.xml
CONFIG_SOFTFLOAT=yes
TARGET_HAS_BFLT=yes
